package translation

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

const claudeOAuthToolPrefix = "proxy_"

// numberValue returns a float64 for int or float64 map values.
func numberValue(m map[string]any, key string) float64 {
	v, ok := m[key]
	if !ok {
		return 0
	}
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	case int64:
		return float64(n)
	}
	return 0
}

// sanitizeToolArgs fixes bad tool-call params generated by non-Anthropic models.
func sanitizeToolArgs(toolName string, argsJSON string) string {
	var args map[string]any
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return argsJSON
	}
	name := toolName
	if strings.HasPrefix(name, claudeOAuthToolPrefix) {
		name = name[len(claudeOAuthToolPrefix):]
	}
	if name == "Read" {
		sanitizeReadArgs(args)
	}
	b, err := json.Marshal(args)
	if err != nil {
		return argsJSON
	}
	return string(b)
}

func sanitizeReadArgs(args map[string]any) {
	if limit, ok := args["limit"].(string); ok {
		if isDigits(limit) {
			if n, err := strconv.Atoi(limit); err == nil {
				args["limit"] = float64(n)
			}
		}
	}
	if offset, ok := args["offset"].(string); ok {
		if isSignedDigits(offset) {
			if n, err := strconv.Atoi(offset); err == nil {
				args["offset"] = float64(n)
			}
		}
	}

	if limit, ok := args["limit"].(float64); ok {
		if limit > 2000 {
			args["limit"] = 2000
		}
		if limit < 1 {
			delete(args, "limit")
		}
	}
	if offset, ok := args["offset"].(float64); ok && offset < 0 {
		args["offset"] = 0
	}

	if _, hasPages := args["pages"]; hasPages {
		filePath, _ := args["file_path"].(string)
		pages, _ := args["pages"].(string)
		if !isValidPDFPagesArg(filePath, pages) {
			delete(args, "pages")
		}
	}
}

func isDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return s != ""
}

func isSignedDigits(s string) bool {
	if s == "" {
		return false
	}
	i := 0
	if s[0] == '-' {
		i = 1
	}
	for ; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

func isValidPDFPagesArg(filePath, pages string) bool {
	if !strings.HasSuffix(strings.ToLower(filePath), ".pdf") {
		return false
	}
	if pages == "" {
		return false
	}
	for _, c := range pages {
		if (c < '0' || c > '9') && c != '-' {
			return false
		}
	}
	return true
}

func stopThinkingBlock(state *StreamState, results []map[string]any) []map[string]any {
	if !state.ThinkingBlockStarted {
		return results
	}
	results = append(results, map[string]any{
		"type":  "content_block_stop",
		"index": state.ThinkingBlockIndex,
	})
	state.ThinkingBlockStarted = false
	return results
}

func stopTextBlock(state *StreamState, results []map[string]any) []map[string]any {
	if !state.TextBlockStarted || state.TextBlockClosed {
		return results
	}
	state.TextBlockClosed = true
	results = append(results, map[string]any{
		"type":  "content_block_stop",
		"index": state.TextBlockIndex,
	})
	state.TextBlockStarted = false
	return results
}

// openaiToClaudeResponse converts an OpenAI stream chunk into Claude-format
// events. It buffers tool-call argument deltas and emits sanitized input on
// finish_reason.
func openaiToClaudeResponse(chunk map[string]any, state *StreamState) ([]map[string]any, error) {
	if chunk == nil {
		return nil, nil
	}
	choicesRaw, ok := chunk["choices"].([]any)
	if !ok || len(choicesRaw) == 0 {
		return nil, nil
	}
	choice, ok := choicesRaw[0].(map[string]any)
	if !ok {
		return nil, nil
	}
	delta, _ := choice["delta"].(map[string]any)

	results := make([]map[string]any, 0)

	// Track usage.
	if usageRaw, ok := chunk["usage"].(map[string]any); ok && usageRaw != nil {
		promptTokens := int(numberValue(usageRaw, "prompt_tokens"))
		outputTokens := int(numberValue(usageRaw, "completion_tokens"))

		cacheReadTokens := 0
		cacheCreateTokens := 0
		if details, ok := usageRaw["prompt_tokens_details"].(map[string]any); ok {
			cacheReadTokens = int(numberValue(details, "cached_tokens"))
			cacheCreateTokens = int(numberValue(details, "cache_creation_tokens"))
		}

		inputTokens := promptTokens - cacheReadTokens - cacheCreateTokens
		usage := map[string]any{
			"input_tokens":  float64(inputTokens),
			"output_tokens": float64(outputTokens),
		}
		if cacheReadTokens > 0 {
			usage["cache_read_input_tokens"] = float64(cacheReadTokens)
		}
		if cacheCreateTokens > 0 {
			usage["cache_creation_input_tokens"] = float64(cacheCreateTokens)
		}
		state.Usage = usage
	}

	// First chunk emits message_start.
	if !state.MessageStartSent {
		state.MessageStartSent = true
		state.MessageID = messageIDFromChunk(chunk)
		state.Model = "unknown"
		if m, ok := chunk["model"].(string); ok && m != "" {
			state.Model = m
		}
		state.NextBlockIndex = 0
		results = append(results, map[string]any{
			"type": "message_start",
			"message": map[string]any{
				"id":            state.MessageID,
				"type":          "message",
				"role":          "assistant",
				"model":         state.Model,
				"content":       []any{},
				"stop_reason":   nil,
				"stop_sequence": nil,
				"usage": map[string]any{
					"input_tokens":  0,
					"output_tokens": 0,
				},
			},
		})
	}

	// Reasoning content starts a thinking block.
	reasoningContent := ""
	if rc, ok := delta["reasoning_content"].(string); ok && rc != "" {
		reasoningContent = rc
	} else if rc, ok := delta["reasoning"].(string); ok && rc != "" {
		reasoningContent = rc
	}
	if reasoningContent != "" {
		results = stopTextBlock(state, results)
		if !state.ThinkingBlockStarted {
			state.ThinkingBlockIndex = state.NextBlockIndex
			state.NextBlockIndex++
			state.ThinkingBlockStarted = true
			results = append(results, map[string]any{
				"type":  "content_block_start",
				"index": state.ThinkingBlockIndex,
				"content_block": map[string]any{
					"type":     "thinking",
					"thinking": "",
				},
			})
		}
		results = append(results, map[string]any{
			"type":  "content_block_delta",
			"index": state.ThinkingBlockIndex,
			"delta": map[string]any{
				"type":     "thinking_delta",
				"thinking": reasoningContent,
			},
		})
	}

	// Regular content starts a text block.
	if content, ok := delta["content"].(string); ok && content != "" {
		results = stopThinkingBlock(state, results)
		if !state.TextBlockStarted {
			state.TextBlockIndex = state.NextBlockIndex
			state.NextBlockIndex++
			state.TextBlockStarted = true
			state.TextBlockClosed = false
			results = append(results, map[string]any{
				"type":  "content_block_start",
				"index": state.TextBlockIndex,
				"content_block": map[string]any{
					"type": "text",
					"text": "",
				},
			})
		}
		results = append(results, map[string]any{
			"type":  "content_block_delta",
			"index": state.TextBlockIndex,
			"delta": map[string]any{
				"type": "text_delta",
				"text": content,
			},
		})
	}

	// Tool calls.
	if tcsRaw, ok := delta["tool_calls"].([]any); ok {
		for _, tcRaw := range tcsRaw {
			tc, ok := tcRaw.(map[string]any)
			if !ok {
				continue
			}
			idx := 0
			if n, ok := tc["index"].(float64); ok {
				idx = int(n)
			}

			if id, ok := tc["id"].(string); ok && id != "" {
				results = stopThinkingBlock(state, results)
				results = stopTextBlock(state, results)
				blockIndex := state.NextBlockIndex
				state.NextBlockIndex++

				toolName := ""
				if fn, ok := tc["function"].(map[string]any); ok {
					if name, ok := fn["name"].(string); ok {
						toolName = name
					}
				}
				state.ToolCalls[idx] = ToolCallInfo{
					ID:         id,
					Name:       toolName,
					BlockIndex: blockIndex,
				}

				displayName := toolName
				if strings.HasPrefix(displayName, claudeOAuthToolPrefix) {
					displayName = displayName[len(claudeOAuthToolPrefix):]
				}
				results = append(results, map[string]any{
					"type":  "content_block_start",
					"index": blockIndex,
					"content_block": map[string]any{
						"type":  "tool_use",
						"id":    id,
						"name":  displayName,
						"input": map[string]any{},
					},
				})
			}

			if fn, ok := tc["function"].(map[string]any); ok {
				if args, ok := fn["arguments"].(string); ok && args != "" {
					if info, ok := state.ToolCalls[idx]; ok {
						_ = info
						state.ToolArgBuffers[idx] += args
					}
				}
			}
		}
	}

	// Finish reason.
	if finishReason, ok := choice["finish_reason"].(string); ok && finishReason != "" {
		results = stopThinkingBlock(state, results)
		results = stopTextBlock(state, results)

		// Iterate in ascending tool-call index order: JS Map preserves
		// insertion order (openai-to-claude.js:240-258); Go maps do not.
		indices := make([]int, 0, len(state.ToolCalls))
		for idx := range state.ToolCalls {
			indices = append(indices, idx)
		}
		sort.Ints(indices)
		for _, idx := range indices {
			info := state.ToolCalls[idx]
			if buf, ok := state.ToolArgBuffers[idx]; ok && buf != "" {
				sanitized := sanitizeToolArgs(info.Name, buf)
				results = append(results, map[string]any{
					"type":  "content_block_delta",
					"index": info.BlockIndex,
					"delta": map[string]any{
						"type":        "input_json_delta",
						"partial_json": sanitized,
					},
				})
			}
			results = append(results, map[string]any{
				"type":  "content_block_stop",
				"index": info.BlockIndex,
			})
		}

		state.FinishReason = finishReason
		usage := state.Usage
		if usage == nil {
			usage = map[string]any{"input_tokens": 0, "output_tokens": 0}
		}
		results = append(results, map[string]any{
			"type": "message_delta",
			"delta": map[string]any{
				"stop_reason": convertFinishReason(finishReason),
			},
			"usage": usage,
		})
		results = append(results, map[string]any{"type": "message_stop"})
	}

	if len(results) == 0 {
		return nil, nil
	}
	return results, nil
}

func messageIDFromChunk(chunk map[string]any) string {
	id := ""
	if s, ok := chunk["id"].(string); ok {
		id = strings.TrimPrefix(s, "chatcmpl-")
	}
	if id == "" || id == "chat" || len(id) < 8 {
		extFields, _ := chunk["extend_fields"].(map[string]any)
		if s, ok := extFields["requestId"].(string); ok && s != "" {
			id = s
		} else if s, ok := extFields["traceId"].(string); ok && s != "" {
			id = s
		}
	}
	if id == "" || len(id) < 8 {
		id = fmt.Sprintf("msg_%d", time.Now().UnixMilli())
	}
	return id
}

func convertFinishReason(reason string) string {
	switch reason {
	case "stop":
		return "end_turn"
	case "length":
		return "max_tokens"
	case "tool_calls":
		return "tool_use"
	default:
		return "end_turn"
	}
}
