/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVirtualKeysRouteImport } from './routes/_app.virtual-keys'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppTunnelsRouteImport } from './routes/_app.tunnels'
import { Route as AppTrafficRouteImport } from './routes/_app.traffic'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoutingRulesRouteImport } from './routes/_app.routing-rules'
import { Route as AppQuotaRouteImport } from './routes/_app.quota'
import { Route as AppProxyPoolsRouteImport } from './routes/_app.proxy-pools'
import { Route as AppPromptsRouteImport } from './routes/_app.prompts'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppModelsRouteImport } from './routes/_app.models'
import { Route as AppModelLimitsRouteImport } from './routes/_app.model-limits'
import { Route as AppMitmRouteImport } from './routes/_app.mitm'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppKeysRouteImport } from './routes/_app.keys'
import { Route as AppGuardrailsRouteImport } from './routes/_app.guardrails'
import { Route as AppFeatureFlagsRouteImport } from './routes/_app.feature-flags'
import { Route as AppEndpointRouteImport } from './routes/_app.endpoint'
import { Route as AppDiagnosticsRouteImport } from './routes/_app.diagnostics'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsoleRouteImport } from './routes/_app.console'
import { Route as AppConnectionsRouteImport } from './routes/_app.connections'
import { Route as AppCombosRouteImport } from './routes/_app.combos'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAliasesRouteImport } from './routes/_app.aliases'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppProvidersIndexRouteImport } from './routes/_app.providers.index'
import { Route as AppMcpIndexRouteImport } from './routes/_app.mcp.index'
import { Route as AppProvidersIdRouteImport } from './routes/_app.providers.$id'
import { Route as AppMcpToolsRouteImport } from './routes/_app.mcp.tools'
import { Route as AppMcpToolGroupsRouteImport } from './routes/_app.mcp.tool-groups'
import { Route as AppMcpInstancesRouteImport } from './routes/_app.mcp.instances'
import { Route as AppMcpAccountsRouteImport } from './routes/_app.mcp.accounts'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVirtualKeysRoute = AppVirtualKeysRouteImport.update({
  id: '/virtual-keys',
  path: '/virtual-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppTunnelsRoute = AppTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AppRoute,
} as any)
const AppTrafficRoute = AppTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRulesRoute = AppRoutingRulesRouteImport.update({
  id: '/routing-rules',
  path: '/routing-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotaRoute = AppQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => AppRoute,
} as any)
const AppProxyPoolsRoute = AppProxyPoolsRouteImport.update({
  id: '/proxy-pools',
  path: '/proxy-pools',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppModelLimitsRoute = AppModelLimitsRouteImport.update({
  id: '/model-limits',
  path: '/model-limits',
  getParentRoute: () => AppRoute,
} as any)
const AppMitmRoute = AppMitmRouteImport.update({
  id: '/mitm',
  path: '/mitm',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardrailsRoute = AppGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => AppRoute,
} as any)
const AppFeatureFlagsRoute = AppFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointRoute = AppEndpointRouteImport.update({
  id: '/endpoint',
  path: '/endpoint',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticsRoute = AppDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppCombosRoute = AppCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAliasesRoute = AppAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpIndexRoute = AppMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIdRoute = AppProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpToolsRoute = AppMcpToolsRouteImport.update({
  id: '/mcp/tools',
  path: '/mcp/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpToolGroupsRoute = AppMcpToolGroupsRouteImport.update({
  id: '/mcp/tool-groups',
  path: '/mcp/tool-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpInstancesRoute = AppMcpInstancesRouteImport.update({
  id: '/mcp/instances',
  path: '/mcp/instances',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpAccountsRoute = AppMcpAccountsRouteImport.update({
  id: '/mcp/accounts',
  path: '/mcp/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/alerts': typeof AppAlertsRoute
  '/aliases': typeof AppAliasesRoute
  '/audit': typeof AppAuditRoute
  '/chat': typeof AppChatRoute
  '/combos': typeof AppCombosRoute
  '/connections': typeof AppConnectionsRoute
  '/console': typeof AppConsoleRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/endpoint': typeof AppEndpointRoute
  '/feature-flags': typeof AppFeatureFlagsRoute
  '/guardrails': typeof AppGuardrailsRoute
  '/keys': typeof AppKeysRoute
  '/logs': typeof AppLogsRoute
  '/mitm': typeof AppMitmRoute
  '/model-limits': typeof AppModelLimitsRoute
  '/models': typeof AppModelsRoute
  '/pricing': typeof AppPricingRoute
  '/prompts': typeof AppPromptsRoute
  '/proxy-pools': typeof AppProxyPoolsRoute
  '/quota': typeof AppQuotaRoute
  '/routing-rules': typeof AppRoutingRulesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/teams': typeof AppTeamsRoute
  '/traffic': typeof AppTrafficRoute
  '/tunnels': typeof AppTunnelsRoute
  '/usage': typeof AppUsageRoute
  '/virtual-keys': typeof AppVirtualKeysRoute
  '/mcp/accounts': typeof AppMcpAccountsRoute
  '/mcp/instances': typeof AppMcpInstancesRoute
  '/mcp/tool-groups': typeof AppMcpToolGroupsRoute
  '/mcp/tools': typeof AppMcpToolsRoute
  '/providers/$id': typeof AppProvidersIdRoute
  '/mcp/': typeof AppMcpIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/alerts': typeof AppAlertsRoute
  '/aliases': typeof AppAliasesRoute
  '/audit': typeof AppAuditRoute
  '/chat': typeof AppChatRoute
  '/combos': typeof AppCombosRoute
  '/connections': typeof AppConnectionsRoute
  '/console': typeof AppConsoleRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/endpoint': typeof AppEndpointRoute
  '/feature-flags': typeof AppFeatureFlagsRoute
  '/guardrails': typeof AppGuardrailsRoute
  '/keys': typeof AppKeysRoute
  '/logs': typeof AppLogsRoute
  '/mitm': typeof AppMitmRoute
  '/model-limits': typeof AppModelLimitsRoute
  '/models': typeof AppModelsRoute
  '/pricing': typeof AppPricingRoute
  '/prompts': typeof AppPromptsRoute
  '/proxy-pools': typeof AppProxyPoolsRoute
  '/quota': typeof AppQuotaRoute
  '/routing-rules': typeof AppRoutingRulesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/teams': typeof AppTeamsRoute
  '/traffic': typeof AppTrafficRoute
  '/tunnels': typeof AppTunnelsRoute
  '/usage': typeof AppUsageRoute
  '/virtual-keys': typeof AppVirtualKeysRoute
  '/mcp/accounts': typeof AppMcpAccountsRoute
  '/mcp/instances': typeof AppMcpInstancesRoute
  '/mcp/tool-groups': typeof AppMcpToolGroupsRoute
  '/mcp/tools': typeof AppMcpToolsRoute
  '/providers/$id': typeof AppProvidersIdRoute
  '/mcp': typeof AppMcpIndexRoute
  '/providers': typeof AppProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/aliases': typeof AppAliasesRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/combos': typeof AppCombosRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/console': typeof AppConsoleRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diagnostics': typeof AppDiagnosticsRoute
  '/_app/endpoint': typeof AppEndpointRoute
  '/_app/feature-flags': typeof AppFeatureFlagsRoute
  '/_app/guardrails': typeof AppGuardrailsRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/mitm': typeof AppMitmRoute
  '/_app/model-limits': typeof AppModelLimitsRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/prompts': typeof AppPromptsRoute
  '/_app/proxy-pools': typeof AppProxyPoolsRoute
  '/_app/quota': typeof AppQuotaRoute
  '/_app/routing-rules': typeof AppRoutingRulesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/traffic': typeof AppTrafficRoute
  '/_app/tunnels': typeof AppTunnelsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/virtual-keys': typeof AppVirtualKeysRoute
  '/_app/mcp/accounts': typeof AppMcpAccountsRoute
  '/_app/mcp/instances': typeof AppMcpInstancesRoute
  '/_app/mcp/tool-groups': typeof AppMcpToolGroupsRoute
  '/_app/mcp/tools': typeof AppMcpToolsRoute
  '/_app/providers/$id': typeof AppProvidersIdRoute
  '/_app/mcp/': typeof AppMcpIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/alerts'
    | '/aliases'
    | '/audit'
    | '/chat'
    | '/combos'
    | '/connections'
    | '/console'
    | '/dashboard'
    | '/diagnostics'
    | '/endpoint'
    | '/feature-flags'
    | '/guardrails'
    | '/keys'
    | '/logs'
    | '/mitm'
    | '/model-limits'
    | '/models'
    | '/pricing'
    | '/prompts'
    | '/proxy-pools'
    | '/quota'
    | '/routing-rules'
    | '/settings'
    | '/skills'
    | '/teams'
    | '/traffic'
    | '/tunnels'
    | '/usage'
    | '/virtual-keys'
    | '/mcp/accounts'
    | '/mcp/instances'
    | '/mcp/tool-groups'
    | '/mcp/tools'
    | '/providers/$id'
    | '/mcp/'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/alerts'
    | '/aliases'
    | '/audit'
    | '/chat'
    | '/combos'
    | '/connections'
    | '/console'
    | '/dashboard'
    | '/diagnostics'
    | '/endpoint'
    | '/feature-flags'
    | '/guardrails'
    | '/keys'
    | '/logs'
    | '/mitm'
    | '/model-limits'
    | '/models'
    | '/pricing'
    | '/prompts'
    | '/proxy-pools'
    | '/quota'
    | '/routing-rules'
    | '/settings'
    | '/skills'
    | '/teams'
    | '/traffic'
    | '/tunnels'
    | '/usage'
    | '/virtual-keys'
    | '/mcp/accounts'
    | '/mcp/instances'
    | '/mcp/tool-groups'
    | '/mcp/tools'
    | '/providers/$id'
    | '/mcp'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/alerts'
    | '/_app/aliases'
    | '/_app/audit'
    | '/_app/chat'
    | '/_app/combos'
    | '/_app/connections'
    | '/_app/console'
    | '/_app/dashboard'
    | '/_app/diagnostics'
    | '/_app/endpoint'
    | '/_app/feature-flags'
    | '/_app/guardrails'
    | '/_app/keys'
    | '/_app/logs'
    | '/_app/mitm'
    | '/_app/model-limits'
    | '/_app/models'
    | '/_app/pricing'
    | '/_app/prompts'
    | '/_app/proxy-pools'
    | '/_app/quota'
    | '/_app/routing-rules'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/teams'
    | '/_app/traffic'
    | '/_app/tunnels'
    | '/_app/usage'
    | '/_app/virtual-keys'
    | '/_app/mcp/accounts'
    | '/_app/mcp/instances'
    | '/_app/mcp/tool-groups'
    | '/_app/mcp/tools'
    | '/_app/providers/$id'
    | '/_app/mcp/'
    | '/_app/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/virtual-keys': {
      id: '/_app/virtual-keys'
      path: '/virtual-keys'
      fullPath: '/virtual-keys'
      preLoaderRoute: typeof AppVirtualKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tunnels': {
      id: '/_app/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof AppTunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traffic': {
      id: '/_app/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof AppTrafficRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing-rules': {
      id: '/_app/routing-rules'
      path: '/routing-rules'
      fullPath: '/routing-rules'
      preLoaderRoute: typeof AppRoutingRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quota': {
      id: '/_app/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof AppQuotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proxy-pools': {
      id: '/_app/proxy-pools'
      path: '/proxy-pools'
      fullPath: '/proxy-pools'
      preLoaderRoute: typeof AppProxyPoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/model-limits': {
      id: '/_app/model-limits'
      path: '/model-limits'
      fullPath: '/model-limits'
      preLoaderRoute: typeof AppModelLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mitm': {
      id: '/_app/mitm'
      path: '/mitm'
      fullPath: '/mitm'
      preLoaderRoute: typeof AppMitmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guardrails': {
      id: '/_app/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof AppGuardrailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feature-flags': {
      id: '/_app/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof AppFeatureFlagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/endpoint': {
      id: '/_app/endpoint'
      path: '/endpoint'
      fullPath: '/endpoint'
      preLoaderRoute: typeof AppEndpointRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostics': {
      id: '/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/console': {
      id: '/_app/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/combos': {
      id: '/_app/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AppCombosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aliases': {
      id: '/_app/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AppAliasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/': {
      id: '/_app/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof AppMcpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/$id': {
      id: '/_app/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof AppProvidersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/tools': {
      id: '/_app/mcp/tools'
      path: '/mcp/tools'
      fullPath: '/mcp/tools'
      preLoaderRoute: typeof AppMcpToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/tool-groups': {
      id: '/_app/mcp/tool-groups'
      path: '/mcp/tool-groups'
      fullPath: '/mcp/tool-groups'
      preLoaderRoute: typeof AppMcpToolGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/instances': {
      id: '/_app/mcp/instances'
      path: '/mcp/instances'
      fullPath: '/mcp/instances'
      preLoaderRoute: typeof AppMcpInstancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/accounts': {
      id: '/_app/mcp/accounts'
      path: '/mcp/accounts'
      fullPath: '/mcp/accounts'
      preLoaderRoute: typeof AppMcpAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAliasesRoute: typeof AppAliasesRoute
  AppAuditRoute: typeof AppAuditRoute
  AppChatRoute: typeof AppChatRoute
  AppCombosRoute: typeof AppCombosRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppConsoleRoute: typeof AppConsoleRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiagnosticsRoute: typeof AppDiagnosticsRoute
  AppEndpointRoute: typeof AppEndpointRoute
  AppFeatureFlagsRoute: typeof AppFeatureFlagsRoute
  AppGuardrailsRoute: typeof AppGuardrailsRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMitmRoute: typeof AppMitmRoute
  AppModelLimitsRoute: typeof AppModelLimitsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppPricingRoute: typeof AppPricingRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppProxyPoolsRoute: typeof AppProxyPoolsRoute
  AppQuotaRoute: typeof AppQuotaRoute
  AppRoutingRulesRoute: typeof AppRoutingRulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTrafficRoute: typeof AppTrafficRoute
  AppTunnelsRoute: typeof AppTunnelsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppVirtualKeysRoute: typeof AppVirtualKeysRoute
  AppMcpAccountsRoute: typeof AppMcpAccountsRoute
  AppMcpInstancesRoute: typeof AppMcpInstancesRoute
  AppMcpToolGroupsRoute: typeof AppMcpToolGroupsRoute
  AppMcpToolsRoute: typeof AppMcpToolsRoute
  AppProvidersIdRoute: typeof AppProvidersIdRoute
  AppMcpIndexRoute: typeof AppMcpIndexRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAliasesRoute: AppAliasesRoute,
  AppAuditRoute: AppAuditRoute,
  AppChatRoute: AppChatRoute,
  AppCombosRoute: AppCombosRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppConsoleRoute: AppConsoleRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiagnosticsRoute: AppDiagnosticsRoute,
  AppEndpointRoute: AppEndpointRoute,
  AppFeatureFlagsRoute: AppFeatureFlagsRoute,
  AppGuardrailsRoute: AppGuardrailsRoute,
  AppKeysRoute: AppKeysRoute,
  AppLogsRoute: AppLogsRoute,
  AppMitmRoute: AppMitmRoute,
  AppModelLimitsRoute: AppModelLimitsRoute,
  AppModelsRoute: AppModelsRoute,
  AppPricingRoute: AppPricingRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppProxyPoolsRoute: AppProxyPoolsRoute,
  AppQuotaRoute: AppQuotaRoute,
  AppRoutingRulesRoute: AppRoutingRulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTrafficRoute: AppTrafficRoute,
  AppTunnelsRoute: AppTunnelsRoute,
  AppUsageRoute: AppUsageRoute,
  AppVirtualKeysRoute: AppVirtualKeysRoute,
  AppMcpAccountsRoute: AppMcpAccountsRoute,
  AppMcpInstancesRoute: AppMcpInstancesRoute,
  AppMcpToolGroupsRoute: AppMcpToolGroupsRoute,
  AppMcpToolsRoute: AppMcpToolsRoute,
  AppProvidersIdRoute: AppProvidersIdRoute,
  AppMcpIndexRoute: AppMcpIndexRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
