package cli

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

type installOptions struct {
	User            bool
	Root            string
	HomeDir         string
	Executable      string
	RunCommand      func(string, ...string) error
	SecretGenerator func() (string, error)
	Out             io.Writer
}

const deployServiceTemplate = `[Unit]
Description=g0router LLM Gateway
Documentation=https://github.com/bloodf/g0router
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=g0router
Group=g0router
EnvironmentFile=-/etc/default/g0router
ExecStart=/usr/local/bin/g0router serve
Restart=on-failure
RestartSec=5s
StartLimitIntervalSec=60s
StartLimitBurst=5

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/g0router
PrivateTmp=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
MemoryDenyWriteExecute=true
LockPersonality=true

StandardOutput=journal
StandardError=journal
SyslogIdentifier=g0router

[Install]
WantedBy=multi-user.target
`

const deployDefaultTemplate = `# /etc/default/g0router
PORT=20128
DATA_DIR=/var/lib/g0router

# Generated by g0router install. Rotate with: openssl rand -hex 32
JWT_SECRET=
API_KEY_SECRET=

REQUIRE_API_KEY=true
ENABLE_REQUEST_LOGS=false
RTK_ENABLED=true
CAVEMAN_ENABLED=false
CAVEMAN_LEVEL=full

# HTTPS_PROXY=http://proxy:8080
`

// NewInstallCommand builds the systemd install command.
func NewInstallCommand() *cobra.Command {
	var user bool

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install g0router as a systemd service",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInstall(newInstallOptions(cmd.OutOrStdout(), user))
		},
	}
	cmd.Flags().BoolVar(&user, "user", false, "install as a user systemd service")
	return cmd
}

func newUninstallCommand() *cobra.Command {
	var user bool

	cmd := &cobra.Command{
		Use:   "uninstall",
		Short: "Uninstall the g0router systemd service",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runUninstall(newInstallOptions(cmd.OutOrStdout(), user))
		},
	}
	cmd.Flags().BoolVar(&user, "user", false, "uninstall the user systemd service")
	return cmd
}

func newInstallOptions(out io.Writer, user bool) installOptions {
	home, _ := os.UserHomeDir()
	exe, _ := os.Executable()
	return installOptions{
		User:            user,
		Root:            string(filepath.Separator),
		HomeDir:         home,
		Executable:      exe,
		RunCommand:      runCommand,
		SecretGenerator: generateInstallSecret,
		Out:             out,
	}
}

func runInstall(options installOptions) error {
	options = normalizeInstallOptions(options)
	paths := installPaths(options)

	if !options.User {
		if err := ensureSystemUser(options.RunCommand); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(filepath.Dir(paths.Binary), 0o755); err != nil {
		return fmt.Errorf("create binary dir: %w", err)
	}
	if err := copyFile(options.Executable, paths.Binary, 0o755); err != nil {
		return fmt.Errorf("install binary: %w", err)
	}
	if err := os.MkdirAll(paths.DataDir, 0o755); err != nil {
		return fmt.Errorf("create data dir: %w", err)
	}
	if !options.User {
		if err := options.RunCommand("chown", "g0router:g0router", paths.DataDir); err != nil {
			return fmt.Errorf("set data dir owner: %w", err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(paths.Service), 0o755); err != nil {
		return fmt.Errorf("create service dir: %w", err)
	}

	serviceBinary := paths.Binary
	serviceDataDir := paths.DataDir
	if !options.User {
		serviceBinary = "/usr/local/bin/g0router"
		serviceDataDir = "/var/lib/g0router"
	}
	service, err := serviceTemplate(serviceBinary, serviceDataDir, options.User)
	if err != nil {
		return err
	}
	if err := os.WriteFile(paths.Service, []byte(service), 0o644); err != nil {
		return fmt.Errorf("write service: %w", err)
	}
	if paths.Defaults != "" {
		if err := os.MkdirAll(filepath.Dir(paths.Defaults), 0o755); err != nil {
			return fmt.Errorf("create defaults dir: %w", err)
		}
		defaults, err := readDeployTemplate("g0router.default")
		if err != nil {
			return fmt.Errorf("read default template: %w", err)
		}
		defaults, err = renderDefaultTemplate(defaults, options.SecretGenerator)
		if err != nil {
			return fmt.Errorf("render defaults: %w", err)
		}
		if err := os.WriteFile(paths.Defaults, defaults, 0o644); err != nil {
			return fmt.Errorf("write defaults: %w", err)
		}
	}

	if err := options.RunCommand("systemctl", paths.SystemctlArgs("daemon-reload")...); err != nil {
		return fmt.Errorf("reload systemd: %w", err)
	}
	if err := options.RunCommand("systemctl", paths.SystemctlArgs("enable", "--now", "g0router")...); err != nil {
		return fmt.Errorf("enable service: %w", err)
	}

	if options.User {
		fmt.Fprintf(options.Out, "installed user service: %s\n", displayPath(paths.Service, options))
		return nil
	}
	fmt.Fprintf(options.Out, "installed system service: %s\n", displayPath(paths.Service, options))
	return nil
}

func runUninstall(options installOptions) error {
	options = normalizeInstallOptions(options)
	paths := installPaths(options)

	if err := options.RunCommand("systemctl", paths.SystemctlArgs("disable", "--now", "g0router")...); err != nil {
		return fmt.Errorf("disable service: %w", err)
	}
	for _, path := range []string{paths.Service, paths.Defaults, paths.Binary} {
		if path == "" {
			continue
		}
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove %s: %w", path, err)
		}
	}
	if err := options.RunCommand("systemctl", paths.SystemctlArgs("daemon-reload")...); err != nil {
		return fmt.Errorf("reload systemd: %w", err)
	}
	fmt.Fprintf(options.Out, "removed service; kept data in %s\n", displayPath(paths.DataDir, options))
	return nil
}

type resolvedInstallPaths struct {
	Binary   string
	Service  string
	Defaults string
	DataDir  string
	User     bool
}

func (p resolvedInstallPaths) SystemctlArgs(args ...string) []string {
	if !p.User {
		return args
	}
	return append([]string{"--user"}, args...)
}

func installPaths(options installOptions) resolvedInstallPaths {
	if options.User {
		return resolvedInstallPaths{
			Binary:  filepath.Join(options.HomeDir, ".local", "bin", "g0router"),
			Service: filepath.Join(options.HomeDir, ".config", "systemd", "user", "g0router.service"),
			DataDir: filepath.Join(options.HomeDir, ".g0router"),
			User:    true,
		}
	}
	return resolvedInstallPaths{
		Binary:   rooted(options.Root, "/usr/local/bin/g0router"),
		Service:  rooted(options.Root, "/etc/systemd/system/g0router.service"),
		Defaults: rooted(options.Root, "/etc/default/g0router"),
		DataDir:  rooted(options.Root, "/var/lib/g0router"),
	}
}

func normalizeInstallOptions(options installOptions) installOptions {
	if options.Root == "" {
		options.Root = string(filepath.Separator)
	}
	if options.HomeDir == "" {
		options.HomeDir, _ = os.UserHomeDir()
	}
	if options.Executable == "" {
		options.Executable, _ = os.Executable()
	}
	if options.RunCommand == nil {
		options.RunCommand = runCommand
	}
	if options.SecretGenerator == nil {
		options.SecretGenerator = generateInstallSecret
	}
	if options.Out == nil {
		options.Out = io.Discard
	}
	return options
}

func rooted(root, absolute string) string {
	if root == string(filepath.Separator) {
		return absolute
	}
	return filepath.Join(root, strings.TrimPrefix(absolute, string(filepath.Separator)))
}

func serviceTemplate(binary, dataDir string, user bool) (string, error) {
	content, err := readDeployTemplate("g0router.service")
	if err != nil {
		return "", fmt.Errorf("read service template: %w", err)
	}
	service := strings.ReplaceAll(string(content), "/usr/local/bin/g0router", binary)
	service = strings.ReplaceAll(service, "/var/lib/g0router", dataDir)
	if user {
		service = omitServiceLines(service, "User=", "Group=", "EnvironmentFile=", "ProtectHome=")
		service = strings.ReplaceAll(service, "WantedBy=multi-user.target", "WantedBy=default.target")
	}
	return service, nil
}

func omitServiceLines(content string, prefixes ...string) string {
	lines := strings.Split(content, "\n")
	filtered := lines[:0]
	for _, line := range lines {
		omit := false
		for _, prefix := range prefixes {
			if strings.HasPrefix(line, prefix) {
				omit = true
				break
			}
		}
		if !omit {
			filtered = append(filtered, line)
		}
	}
	return strings.Join(filtered, "\n")
}

func ensureSystemUser(run func(string, ...string) error) error {
	if err := run("id", "-u", "g0router"); err == nil {
		return nil
	}
	if err := run("useradd", "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", "g0router"); err != nil {
		return fmt.Errorf("create g0router user: %w", err)
	}
	return nil
}

func readDeployTemplate(name string) ([]byte, error) {
	switch name {
	case "g0router.service":
		return []byte(deployServiceTemplate), nil
	case "g0router.default":
		return []byte(deployDefaultTemplate), nil
	}
	for _, candidate := range []string{
		filepath.Join("deploy", name),
		filepath.Join("..", "..", "deploy", name),
	} {
		content, err := os.ReadFile(candidate)
		if err == nil {
			return content, nil
		}
	}
	return nil, fmt.Errorf("deploy template %s not found", name)
}

func renderDefaultTemplate(content []byte, secretGenerator func() (string, error)) ([]byte, error) {
	defaults := string(content)
	for _, key := range []string{"JWT_SECRET", "API_KEY_SECRET"} {
		if !strings.Contains(defaults, key+"=\n") {
			continue
		}
		secret, err := secretGenerator()
		if err != nil {
			return nil, fmt.Errorf("generate %s: %w", key, err)
		}
		defaults = strings.ReplaceAll(defaults, key+"=\n", key+"="+secret+"\n")
	}
	return []byte(defaults), nil
}

func generateInstallSecret() (string, error) {
	var bytes [32]byte
	if _, err := rand.Read(bytes[:]); err != nil {
		return "", fmt.Errorf("read random bytes: %w", err)
	}
	return hex.EncodeToString(bytes[:]), nil
}

func copyFile(src, dst string, mode os.FileMode) error {
	input, err := os.Open(src)
	if err != nil {
		return err
	}
	defer input.Close()
	srcInfo, err := input.Stat()
	if err != nil {
		return err
	}
	if dstInfo, err := os.Stat(dst); err == nil && os.SameFile(srcInfo, dstInfo) {
		return os.Chmod(dst, mode)
	}

	tmp, err := os.CreateTemp(filepath.Dir(dst), ".g0router-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := io.Copy(tmp, input); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, dst)
}

func runCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %s: %w", name, strings.Join(args, " "), strings.TrimSpace(string(output)), err)
	}
	return nil
}

func displayPath(path string, options installOptions) string {
	if options.Root == string(filepath.Separator) || options.User {
		return path
	}
	return string(filepath.Separator) + strings.TrimPrefix(strings.TrimPrefix(path, options.Root), string(filepath.Separator))
}
