package catalog

// providerAliases maps provider aliases and canonical names to provider IDs.
// It is the Go port of ALIAS_TO_PROVIDER_ID in open-sse/services/model.js:2-143.
var providerAliases = map[string]string{
	// Coding assistants
	"cc":        "claude",
	"cx":        "codex",
	"gc":        "gemini-cli",
	"qw":        "qwen",
	"if":        "iflow",
	"ag":        "antigravity",
	"gh":        "github",
	"kr":        "kiro",
	"cu":        "cursor",
	"kc":        "kilocode",
	"kmc":       "kimi-coding",
	"cl":        "cline",
	"oc":        "opencode",
	"ocg":       "opencode-go",
	"qd":        "qoder",
	"qoder":     "qoder",
	// TTS providers
	"el":        "elevenlabs",
	// API Key providers
	"openai":    "openai",
	"vercel":    "vercel-ai-gateway",
	"vercel-ai-gateway": "vercel-ai-gateway",
	"anthropic": "anthropic",
	"gemini":    "gemini",
	"openrouter":"openrouter",
	"glm":       "glm",
	"kimi":      "kimi",
	"minimax":   "minimax",
	"minimax-cn":"minimax-cn",
	"hf":        "huggingface",
	"huggingface": "huggingface",
	"ds":        "deepseek",
	"deepseek":  "deepseek",
	"cmc":       "commandcode",
	"commandcode": "commandcode",
	"groq":      "groq",
	"xai":       "xai",
	"mistral":   "mistral",
	"pplx":      "perplexity",
	"perplexity":"perplexity",
	"together":  "together",
	"fireworks": "fireworks",
	"cerebras":  "cerebras",
	"cohere":    "cohere",
	"nvidia":    "nvidia",
	"nebius":    "nebius",
	"siliconflow": "siliconflow",
	"hyp":       "hyperbolic",
	"hyperbolic":"hyperbolic",
	"dg":        "deepgram",
	"deepgram":  "deepgram",
	"aai":       "assemblyai",
	"assemblyai":"assemblyai",
	"nb":        "nanobanana",
	"nanobanana":"nanobanana",
	"ch":        "chutes",
	"chutes":    "chutes",
	"ark":       "volcengine-ark",
	"volcengine-ark": "volcengine-ark",
	"byteplus":  "byteplus",
	"bpm":       "byteplus",
	"cursor":    "cursor",
	"vx":        "vertex",
	"vertex":    "vertex",
	"vxp":       "vertex-partner",
	"vertex-partner": "vertex-partner",
	// Web cookie providers
	"gw":        "grok-web",
	"grok-web":  "grok-web",
	"pw":        "perplexity-web",
	"perplexity-web": "perplexity-web",
	"mimo":      "xiaomi-mimo",
	"xiaomi-mimo": "xiaomi-mimo",
	"xmtp":      "xiaomi-tokenplan",
	"xiaomi-tokenplan": "xiaomi-tokenplan",
	"cf":        "cloudflare-ai",
	"cloudflare-ai": "cloudflare-ai",
	// Image/video providers
	"fal":       "fal-ai",
	"fal-ai":    "fal-ai",
	"stability": "stability-ai",
	"stability-ai": "stability-ai",
	"bfl":       "black-forest-labs",
	"black-forest-labs": "black-forest-labs",
	"recraft":   "recraft",
	"topaz":     "topaz",
	"runway":    "runwayml",
	"runwayml":  "runwayml",
	// Embedding/rerank
	"jina":      "jina-ai",
	"jina-ai":   "jina-ai",
	// TTS
	"polly":     "aws-polly",
	"aws-polly": "aws-polly",
	// Free-tier providers (synced from OmniRoute)
	"agentrouter": "agentrouter",
	"aimlapi":   "aimlapi",
	"aiml":      "aimlapi",
	"novita":    "novita",
	"modal":     "modal",
	"mdl":       "modal",
	"reka":      "reka",
	"nlpcloud":  "nlpcloud",
	"nlpc":      "nlpcloud",
	"bazaarlink":"bazaarlink",
	"bzl":       "bazaarlink",
	"completions": "completions",
	"cpl":       "completions",
	"enally":    "enally",
	"enly":      "enally",
	"freetheai": "freetheai",
	"fta":       "freetheai",
	"llm7":      "llm7",
	"lepton":    "lepton",
	"kluster":   "kluster",
	"ai21":      "ai21",
	"inference-net": "inference-net",
	"inet":      "inference-net",
	"predibase": "predibase",
	"bytez":     "bytez",
	"morph":     "morph",
	"longcat":   "longcat",
	"lc":        "longcat",
	"puter":     "puter",
	"pu":        "puter",
	"uncloseai": "uncloseai",
	"unc":       "uncloseai",
	"scaleway":  "scaleway",
	"scw":       "scaleway",
	"deepinfra": "deepinfra",
	"sambanova": "sambanova",
	"samba":     "sambanova",
	"nscale":    "nscale",
	"baseten":   "baseten",
	"publicai":  "publicai",
	"nous-research": "nous-research",
	"nous":      "nous-research",
	"glhf":      "glhf",
	"bb":        "blackbox",
	"blackbox":  "blackbox",
}

// ResolveProviderAlias returns the provider ID for the given alias.
// It returns ("", false) when the alias is not known.
func ResolveProviderAlias(alias string) (string, bool) {
	id, ok := providerAliases[alias]
	return id, ok
}

// ProviderAliasCount returns the number of entries in the alias table.
func ProviderAliasCount() int { return len(providerAliases) }

// ForEachProviderAlias calls fn for every alias→providerID pair.
func ForEachProviderAlias(fn func(alias, providerID string)) {
	for a, id := range providerAliases {
		fn(a, id)
	}
}
